name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image pyvcardweb
        run: |
          docker buildx build --push \
            -f Dockerfile_rails --build-arg PYTHON_VERSION=3.9.5 \
            --tag manologcode/pyvcardweb395:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
      - name: build the image nginx_flask
        run: |
          docker buildx build --push \
            -f Dockerfile_nginx119 --build-arg NGINX_VERSION=1.19 \
            --tag manologcode/nginx_flask:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .

